### ISSUE TITLE
What's new - pull in version releases from GitHub

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanillaframework.io#13]
- A page that lists all version releases and some info, plus links to individual release notes - https://github.com/vanilla-framework/vanilla-framework/releases/tag/v1.8.1
- Or a promo section that highlights the latest release and links to https://github.com/vanilla-framework/vanilla-framework/releases

<img width="1439" alt="Screenshot 2019-10-01 at 15 57 13" src="https://user-images.githubusercontent.com/17748020/65974032-29c2b700-e464-11e9-86b1-53ddc440a5b5.png">

**Comment by kwm14** [comment]
## Visual exploration
Few options to display what's new in Vanilla on the homepage.

### 001
![whats-new-001](https://user-images.githubusercontent.com/17748020/65975964-59bf8980-e467-11e9-952a-7539d037eeb4.png)

### 002
![whats-new-002](https://user-images.githubusercontent.com/17748020/65975965-59bf8980-e467-11e9-96bd-24b09ce3585c.png)

### 003
![whats-new-003](https://user-images.githubusercontent.com/17748020/65976989-051d0e00-e469-11e9-9f82-ebfd5f82a71b.png)

@spencerbygraves can I get your design 👀 😉

**Comment by spencerbygraves** [comment]
@kwm14 rather than using cards, I prefer the list in your example above. Could we try something similar?

**Comment by kwm14** [comment]
## Updated exploration
- Remove card styling and put update layout to a list

### 004
![whats-new-004](https://user-images.githubusercontent.com/17748020/66035107-73fa7580-e502-11e9-9985-1bcc41b84711.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Design added to the homepage redesign [issue](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/15). 💯
