### ISSUE TITLE
Add feature blog posts

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanillaframework.io#14]
We've written a couple of posts that are on Vanilla or relate to Vanilla e.g site migrations, it would be good to highlight these on our site.
- Improve engagement
- Promote our posts
- Improve social and community presence

**Comment by deadlight** [comment]
@kwm14 we should make an epic for this task with design and build tasks.

**Comment by kwm14** [comment]
## First exploration
- 2 versions:
  - Using existing styling seen on https://blog.ubuntu.com/
  - Updated version recently designed for upcoming Snapcraft revamp (my preferred choice)
- Obviously not snowed with posts but we plan to do at least another 4 this year 😉 
- @spencerbygraves ready for the first review (be aware orange alert)

### 001
![001-blog-posts](https://user-images.githubusercontent.com/17748020/60113473-becd5a00-9769-11e9-8185-6107d40e14c2.png)

### 002
![002-blog-posts](https://user-images.githubusercontent.com/17748020/60113474-becd5a00-9769-11e9-8b98-3573752a9f9d.png)

**Comment by spencerbygraves** [comment]
@kwm14 thanks, happy to go with 002 as discussed.

**Comment by kwm14** [comment]
Approved design added to build issue [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/2397) 👍
